name: CommandAlert
version: 1.0
main: com.ementalo.commandalert.CommandAlert
authors:
  - ementalo
commands:
  cmdcheck:
    description: Teleports you to the location the commmand was used
    usage: /<command> <id>
  cmdalertr:
    description: Reloads the config file
    usage: /<command>